

parameters : {
  "N" : { 
    min : 1,
    max : 1000
  },
  k : {
    min : 0.5,
    max : 10
  },
  mu : {
    min : 0.5,
    max : 10
  },
  sigma : {
    min : 0.5,
    max : 10
  }
}

replicates : {
  draws_per_parameter : 100,
  size : 1000
}



