
parameters : {
  "N" : {
    min : 1,
    max : 1000
  },
  alpha : {
    min : 0.5,
    max : 10
  },
  beta : {
    min : 0.5,
    max : 10
  },
  nu : {
    min : 0.5,
    max : 10
  }
}

replicates : {
  draws_per_parameter : 100,
  size : 1000
}



