

parameters : {
  "N" : {
    min : 1,
    max : 1000
  },
  alpha : {
    min : 0.5,
    max : 10
  },
  beta : {
    min : 0.5,
    max : 10
  },
  delay_max : {
    min : 400,
    max : 400
  },
  q : {
    min : 0.05,
    max : 0.65
  }
}

replicates : {
  draws_per_parameter : 100,
  size : 1000
}



